# Jekyll Resume Theme

# Site settings
title: Juan Luna
email: contacto@juanluna.co
description: A ver a ver a ver.
baseurl: ""
url: "http://blog.juanluna.co"
name: Juan Luna
job: front end developer & web designer
location: Bogotá, CO
languages: HTML, CSS and Javascript
twitter_username: juanlunaco
github_username:  juanlunaco
codepen_username:  juanlunaco
email_address: some@email.com

# Build settings
markdown: kramdown
